server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testmybatis?useUnicode=true&amp;characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: alex
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.yiyue.lesson.entity
